console.log("============1.============");
var myFullName;
console.log("Before  initialization :",myFullName);
myFullName ="jayshree  kamble";
console.log("after  initialization :",myFullName);
myFullName ="jayshree vishwanath kamble";
console.log("my full name is :",myFullName);
console.log("==============2.============");
var myLove="I Love only JS";
console.log(myLove);
console.log("===============3.==========");
var FirstName="jayshree",lastName="kamble",age="25",address="pune",pin="411014",gender="female",isMarried="yes";
console.log("my first name is : ",FirstName);
console.log("my last name is : ",lastName);
console.log("my age name is : ",age);
console.log("my address is : ",address);
console.log("my PinCode is : ",pin);
console.log("my gender is : ",gender);
console.log("is she married : ",isMarried);
